# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-09 03:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('comment_username', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=100)),
                ('comment_time', models.DateTimeField(default=datetime.datetime(2018, 6, 9, 3, 21, 2, 259144))),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=140)),
                ('comment_count', models.IntegerField(default=0)),
                ('content_time', models.DateTimeField(default=datetime.datetime(2018, 6, 9, 3, 21, 2, 258237))),
            ],
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('follow_username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('follow_count', models.IntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=2)),
                ('intro', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
