# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-09 03:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='contents_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 9, 3, 24, 3, 247007)),
        ),
        migrations.AlterField(
            model_name='contents',
            name='content_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 9, 3, 24, 3, 246619)),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2018, 6, 9, 3, 24, 3, 246092)),
        ),
    ]
